## NumPy
Answer the following questions

### Create an Array
1. Create a 4X2 integer array and print its attributes.

  The element must be a type of unsigned int16

In [ ]:
import numpy

Array01 = numpy.empty([4,2], dtype = numpy.uint16) 
print("Print Array")
print(Array01)

print("Printing numpy array Attributes")
print("Array Shape is: ", Array01.shape)
print("Array dimensions are ", Array01.ndim)
print("Length of each element of array in bytes is ", Array01.itemsize)

Print Array
[[61312 54953]
 [22022     0]
 [    0     0]
 [    0     0]]
Printing numpy array Attributes
Array Shape is:  (4, 2)
Array dimensions are  2
Length of each element of array in bytes is  2


### Slice an Array

2. Create a 5 rows by 4 columns numpy array of random float32 numbers and extract an array of odd rows and even columns from the numpy array.

In [ ]:
import numpy

Array02 = numpy.empty([5,4], dtype = numpy.float32) 
print("Print Array")
print(Array02)

print("\n Printing array of odd rows and even columns")
newArray = Array02[::2, 1::2]
print(newArray)

Print Array
[[-7.2955281e+14  3.0859395e-41  2.8025969e-45  2.3822074e-44]
 [ 3.9236357e-44  0.0000000e+00 -7.2955066e+14  3.0859395e-41]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 1.4012985e-44  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]]

 Printing array of odd rows and even columns
[[3.086e-41 2.382e-44]
 [0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00]]


### 2D Array Manipulation

3. Create a two dimensional array of dimension 4 rows by 5 columns with random integers and replace all the values of the second column of the array with value 5.

In [ ]:
import numpy as np

arr=np.random.randint(100, size=20)
arr_2d=arr.reshape(4,5)    #Reshapes 1d array in to 2d, containing 4 rows and 5 columns.
print(arr_2d)

# replace all the values of the second column of the array with value 5
arr_2d[:, 1] =  5
print(arr_2d)

[[49 37 82 35 50]
 [27 93  9 16  5]
 [90 46 31  7 17]
 [10 47 82  5 31]]
[[49  5 82 35 50]
 [27  5  9 16  5]
 [90  5 31  7 17]
 [10  5 82  5 31]]


Array Operations

4. Add two numpy arrays of random int16 values and take square of each of the element of the resulting array.

In [ ]:
arr1=np.random.randint(1000,size=2, dtype=np.int)
print(arr1)

arr2=np.random.randint(1000,size=2, dtype=np.int)
print(arr2)

arr3= (arr1+arr2)**2
print(arr3)

[711 931]
[229 752]
[ 883600 2832489]


### Array of Random Numbers

5. Generate two numpy lists of 20 random integers each. Create a new numpy list containing odd numbers from the first list and even numbers from the second list.

In [ ]:
list1=list(np.random.randint(100, size=20))
print(list1)

list2=list(np.random.randint(100, size=20))
print(list2)

# get Even numbers from list2 using Lambda function

even_numbers = list(filter(lambda x: x % 2 == 0,list2))
print("Total Even numbers in the list2: ", even_numbers)


# get Odd numbers from list1 using Lambda function

odd_numbers = list(filter(lambda x: x % 2 == 1,list1))
print("Total Odd numbers in the list1: ", odd_numbers)


new_list= odd_numbers + even_numbers
print(new_list)

[8, 65, 35, 55, 0, 56, 53, 49, 49, 40, 59, 35, 87, 60, 36, 30, 65, 81, 34, 50]
[5, 0, 57, 35, 26, 41, 95, 74, 81, 30, 10, 4, 55, 73, 73, 21, 91, 89, 27, 32]
Total Even numbers in the list2:  [0, 26, 74, 30, 10, 4, 32]
Total Odd numbers in the list1:  [65, 35, 55, 53, 49, 49, 59, 35, 87, 65, 81]
[65, 35, 55, 53, 49, 49, 59, 35, 87, 65, 81, 0, 26, 74, 30, 10, 4, 32]


# Data Manipulation using Pandas


We will use the dataset from https://archive.ics.uci.edu/ml/datasets/bank+marketing for this assignment. 

You will click on the data folder link to download bank.zip file.

### Data IO
a. Unzip the **bank.zip** file.

b. Upload **bank.csv** on github.

c. Import the file using url on github in a DataFrame named **bank**.

d. Note that the delimiter is a semi-colon and not comma.

In [ ]:
import pandas as pd

bank = pd.read_csv('https://raw.githubusercontent.com/Mohitul-Haque/Assignment01/main/bank.csv', sep=';')
bank.head()

age          job  marital  education  ... pdays  previous poutcome   y
0   30   unemployed  married    primary  ...    -1         0  unknown  no
1   33     services  married  secondary  ...   339         4  failure  no
2   35   management   single   tertiary  ...   330         1  failure  no
3   30   management  married   tertiary  ...    -1         0  unknown  no
4   59  blue-collar  married  secondary  ...    -1         0  unknown  no

[5 rows x 17 columns]

### Magic Command

a. Create a new folder named **data** in Google Colab. Use magic command **mkdir**.

b. Create a copy of DataFrame in the new folder as **bank01.csv**

In [ ]:
mkdir data


In [ ]:
from pathlib import Path  
filepath = Path('data/bank01.csv')    
bank.to_csv(filepath)

## DataFrame Subsetting

a. Extract a DataFrame of records with **management** and **entrepreneur** job category only.

In [ ]:
df = pd.read_csv('data/bank01.csv')

bank_management = df.loc[(df['job'] == 'management')]

bank_entrepreneur = df.loc[(df['job'] == 'entrepreneur')]

frames = [bank_management, bank_entrepreneur]

#  DataFrame of records with management and entrepreneur job category only
bank_final = pd.concat(frames)
bank_final = bank_final.drop(bank_final.columns[[0]], axis=1)
print(bank_final)

      age           job   marital  education  ... pdays  previous poutcome    y
2      35    management    single   tertiary  ...   330         1  failure   no
3      30    management   married   tertiary  ...    -1         0  unknown   no
5      35    management    single   tertiary  ...   176         3  failure   no
15     40    management   married   tertiary  ...    -1         0  unknown   no
20     38    management  divorced    unknown  ...    -1         0  unknown   no
...   ...           ...       ...        ...  ...   ...       ...      ...  ...
4401   38  entrepreneur  divorced   tertiary  ...    -1         0  unknown   no
4402   41  entrepreneur   married    primary  ...    -1         0  unknown  yes
4487   49  entrepreneur  divorced  secondary  ...    -1         0  unknown   no
4497   31  entrepreneur    single   tertiary  ...    -1         0  unknown   no
4520   44  entrepreneur    single   tertiary  ...   249         7    other   no

[1137 rows x 17 columns]
